KiemKeTaiSan/Areas/QuanTriVien/Controllers/PhanBoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using KiemKeTaiSan.Models;
namespace KiemKeTaiSan.Areas.QuanTriVien.Controllers
{
    public class PhanBoController : Controller
    {
        kktsDataContext db = new kktsDataContext();

        // GET: QuanTriVien/PhanBo
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult XemDanhSachPhanBo()
        {
            return View();
        }

        public ActionResult PhanBoThietBi()
        {
            return View();
        }



        [HttpGet]
        public JsonResult Select_PhanBo()
        {
            var get_data = from s in db.PhanBos
                           group s by s.MaPhong into g
                           join p1 in db.Phongs on g.First().MaPhong equals p1.MaPhong
                           
                           select new { MaPhong = g.First().MaPhong, SoLuong = g.Sum(pc => pc.SoLuong), TenPhong = p1.TenPhong, NgayCapNhat = g.First().NgayCapNhat, NgayTao = g.First().NgayTao };

            return Json(new { data = get_data.OrderByDescending(s => s.NgayCapNhat) }, JsonRequestBehavior.AllowGet);



        }

        [HttpGet]
        public JsonResult Select_PhanBo_By_MaPhong(int MaPhong)
        {
            var get_data = from s in db.PhanBos
                           where s.MaPhong == MaPhong
                           join ts1 in db.TaiSans on s.MaTS equals ts1.MaTS
                           join nts in db.NhomTaiSans on ts1.MaNhomTS equals nts.MaNhomTS
                           select new { 
                               s.MaTS, 
                               ts1.MaNhomTS, 
                               nts.TenNhomTS, 
                               ts1.TenTS, 
                               ts1.GiaTri, 
                               s.SoLuong, 
                               ts1.HangSanXuat, 
                               ts1.NamSanXuat, 
                               ts1.NuocSanXuat, 
                               s.GhiChu, 
                               s.NgayCapNhat 
                           };
            return Json(new { data = get_data.OrderByDescending(s => s.NgayCapNhat) }, JsonRequestBehavior.AllowGet);



        }


        [HttpPost]
        public JsonResult Insert_PhanBo_SoLuong_One(PhanBo pb)
        {
            var check_is = from s in db.PhanBos
                           where s.MaTS == pb.MaTS
                           where s.MaPhong == pb.MaPhong
                           select s; // kiểm tra TS đã có trong phòng chưa

            if (check_is.Count() <= 0) // nếu chưa có 
            {
                try
                {
                    // update lại tài sản
                    var ts = db.TaiSans.SingleOrDefault(s => s.MaTS == pb.MaTS);
                    if (ts.SoLuong >= 1)
                    {
                        if (pb.SoLuong > ts.SoLuong)
                        {
                            return Json(new { Message = "Số lượng không hợp lệ", code = false });
                        }
                        ts.SoLuong -= pb.SoLuong;
                        db.SubmitChanges();

                        // insert vào phân bố
                        pb.NgayTao = DateTime.Now;
                        pb.NgayCapNhat = DateTime.Now;
                        if (string.IsNullOrEmpty(pb.GhiChu))
                        {
                            pb.GhiChu = "Không có";
                        }
                        db.PhanBos.InsertOnSubmit(pb);
                        db.SubmitChanges();
                        return Json(new { Message = "Thêm mới thành công", code = true });
                    }
                    else
                    {
                        return Json(new { Message = "Thêm mới thất bại, do tài sản không đủ số lượng", code = true });
                    }

                }
                catch (Exception ex)
                {
                    return Json(new { Message = ex.Message, code = false });
                }
            }else
            { // nếu có rồi
                try
                {
                    // update lại tài sản
                    var ts = db.TaiSans.SingleOrDefault(s => s.MaTS == pb.MaTS);
                    if (ts.SoLuong >= 1)
                    {
                        if (pb.SoLuong > ts.SoLuong)
                        {
                            return Json(new { Message = "Số lượng không hợp lệ", code = false });
                        }
                        ts.SoLuong -= pb.SoLuong;
                        db.SubmitChanges();

                        // update vào phân bố
                        check_is.SingleOrDefault().NgayCapNhat = DateTime.Now;
                        check_is.SingleOrDefault().SoLuong += pb.SoLuong;
                        if (string.IsNullOrEmpty(pb.GhiChu))
                        {
                            check_is.SingleOrDefault().GhiChu = "Không có";
                        }
                        
                        db.SubmitChanges();
                        return Json(new { Message = "Thêm mới thành công", code = true });
                    }
                    else
                    {
                        return Json(new { Message = "Thêm mới thất bại, do tài sản không đủ số lượng", code = true });
                    }
                }
                catch (Exception ex)
                {
                    return Json(new { Message = ex.Message, code = false });
                }
            }
           
        }



    }
}

KiemKeTaiSan/Areas/QuanTriVien/Controllers/PhongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KiemKeTaiSan.Models;
namespace KiemKeTaiSan.Areas.QuanTriVien.Controllers
{
    public class PhongController : Controller
    {
        kktsDataContext db = new kktsDataContext();
        // GET: QuanTriVien/Phong
        public ActionResult Index()
        {
            var listPhong = from cd in db.Phongs select cd;
            return View(listPhong);
        }

        [HttpGet]
        public JsonResult Select_LoaiPhong()
        {
            var get_data = from s in db.LoaiPhongs.OrderByDescending(a => a.MaLP)
                           select new { s.MaLP, s.TenLP, s.GhiChu, s.NgayCapNhat };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Select_KhuVucPhong()
        {
            var get_data = from s in db.KhuVucPhongs.OrderByDescending(a => a.MaKV)
                           select new { s.MaKV, s.TenKV, s.GhiChu, s.NgayCapNhat };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Select_Phong()
        {
            var get_data = from s in db.Phongs.OrderByDescending(a => a.MaKV)
                           join kvp in db.KhuVucPhongs on s.MaKV equals kvp.MaKV
                           join lp in db.LoaiPhongs on s.MaLP equals lp.MaLP
                           select new {s.MaPhong, s.MaKV, s.MaLP, s.TenPhong, kvp.TenKV, lp.TenLP, s.GhiChu, s.NgayCapNhat };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }

        

    }
}

KiemKeTaiSan/Areas/QuanTriVien/Controllers/TaiSanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KiemKeTaiSan.Models;
namespace KiemKeTaiSan.Areas.QuanTriVien.Controllers
{
    public class TaiSanController : Controller
    {
        kktsDataContext db = new kktsDataContext();

        // GET: QuanTriVien/TaiSan
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult Select_LoaiTaiSan()
        {
            var get_data = from s in db.LoaiTaiSans.OrderByDescending(a => a.MaLoaiTS)
                           select new { s.MaLoaiTS, s.TenLoaiTS, s.GhiChu, s.NgayCapNhat };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Select_NhomTaiSan()
        {
            var get_data = from s in db.NhomTaiSans.OrderByDescending(a => a.MaNhomTS)
                           join lts in db.LoaiTaiSans on s.MaLoaiTS equals lts.MaLoaiTS
                           select new { s.MaLoaiTS, s.MaNhomTS, lts.TenLoaiTS, s.TenNhomTS, s.GhiChu, s.NgayCapNhat };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Select_TaiSan()
        {
            var get_data = from s in db.TaiSans.OrderByDescending(a => a.MaTS)
                           join nts in db.NhomTaiSans on s.MaNhomTS equals nts.MaNhomTS
                           join lts in db.LoaiTaiSans on nts.MaLoaiTS equals lts.MaLoaiTS
                           select new { s.MaTS, s.MaNhomTS, nts.TenNhomTS, lts.MaLoaiTS, lts.TenLoaiTS, s.TenTS, s.GiaTri, s.SoLuong,s.HangSanXuat, s.NamSanXuat, s.NuocSanXuat, s.GhiChu, s.NgayCapNhat };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Select_TaiSan_By_MaTS(int MaTS)
        {
            var get_data = from s in db.TaiSans.OrderByDescending(a => a.MaTS)
                           join nts in db.NhomTaiSans on s.MaNhomTS equals nts.MaNhomTS
                           join lts in db.LoaiTaiSans on nts.MaLoaiTS equals lts.MaLoaiTS
                           where s.MaTS == MaTS
                           select new { s.MaTS, s.MaNhomTS, nts.TenNhomTS, lts.MaLoaiTS, lts.TenLoaiTS, s.TenTS, s.GiaTri, s.SoLuong, s.HangSanXuat, s.NamSanXuat, s.NuocSanXuat, s.GhiChu, s.NgayCapNhat };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }

    }
}

KiemKeTaiSan/Areas/QuanTriVien/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KiemKeTaiSan.Areas.QuanTriVien.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: QuanTriVien/TrangChu
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuTraiPartial()
        {
            return PartialView();
        }







    }
}

KiemKeTaiSan/Areas/QuanTriVien/Views/Shared/FooterPartial.cshtml
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> © Kiểm Kê Tài Sản - TVD - NAT
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>

KiemKeTaiSan/Areas/QuanTriVien/Views/Shared/MenuTraiPartial.cshtml
@{
    Layout = null;
}
<!-- ========== Left Sidebar Start ========== -->
<div class="leftside-menu">
    <!-- LOGO -->
    <a href="#" class="logo text-center logo-light">
        <span class="logo-lg">
            <img src="~/assets/images/Logo_TDMU.png" alt="" height="50">
        </span>
        <span class="logo-sm">
            <img src="~/assets/images/Logo_TDMU.png" alt="" height="61">
        </span>
    </a>
    <!-- LOGO -->
    <a href="index.html" class="logo text-center logo-dark">
        <span class="logo-lg">
            <img src="~/assets/images/logo-dark.png" alt="" height="16">
        </span>
        <span class="logo-sm">
            <img src="~/assets/images/logo_sm_dark.png" alt="" height="16">
        </span>
    </a>
    <div class="h-100" id="leftside-menu-container" data-simplebar>
        <!--- Sidemenu -->
        <ul class="side-nav">
            <li class="side-nav-title side-nav-item"><hr /></li>
            <li class="side-nav-item @ViewBag.ActiveMenu">
                <a href="@Url.Action("Index","TrangChu")" id="test" class="side-nav-link">
                    <i class="uil-home-alt"></i>
                    <span>Trang tổng quan</span>
                    <span class="badge bg-success float-end">1</span>
                </a>
            </li>

            <li class="side-nav-title side-nav-item"><hr /></li>
            <li class="side-nav-item">
                <a href="@Url.Action("Index","NguoiDung")" aria-expanded="false" aria-controls="sidebarQLPhong" class="side-nav-link">
                    <i class="mdi mdi-account-group-outline"></i>
                    <span>Quản lý người dùng</span>
                </a>
            </li>


            <li class="side-nav-item">
                <a href="@Url.Action("Index","Phong")" aria-expanded="false" aria-controls="sidebarQLPhong" class="side-nav-link">
                    <i class="mdi mdi-dots-square"></i>
                    <span>Quản lý phòng</span>
                </a>
            </li>



            <li class="side-nav-item">
                <a href="@Url.Action("Index","TaiSan")" aria-expanded="false" aria-controls="sidebarQLTB" class="side-nav-link">
                    <i class="mdi mdi-desktop-classic"></i>
                    <span>Quản lý tài sản</span>
                </a>
            </li>






            <li class="side-nav-title side-nav-item"><hr /></li>

            <!--
                <li class="side-nav-item">
                    <a href="@Url.Action("XemDanhSachPhanBo","PhanBo")" aria-expanded="false" aria-controls="sidebarDSPB" class="side-nav-link">
                        <i class="dripicons-preview"></i>
                        <span>Xem danh sách phân bố</span>
                    </a>
                </li>
            -->

            <li class="side-nav-item">
                <a href="@Url.Action("PhanBoThietBi","PhanBo")" class="side-nav-link">
                    <i class="dripicons-suitcase"></i>
                    <span>Phân bố tài sản</span>
                </a>
            </li>


            <li class="side-nav-item">
                <a href="@Url.Action("DieuChuyenThietBi","PhanBo")" class="side-nav-link">
                    <i class="mdi mdi-transfer"></i>
                    <span>Điều chuyển tài sản</span>
                </a>
            </li>


            <li class="side-nav-title side-nav-item mt-1"><hr /></li>

            <li class="side-nav-item">
                <a href="#" class="side-nav-link">
                    <i class="dripicons-blog"></i>
                    <span>Nhật ký hoạt động</span>
                </a>
            </li>

        </ul>
        <!-- End Sidebar -->
        <div class="clearfix"></div>
    </div>
    <!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

KiemKeTaiSan/Areas/QuanTriVien/Views/Shared/MenuTrenPartial.cshtml
@{
    Layout = null;
}
<div class="navbar-custom">
    <ul class="list-unstyled topbar-menu float-end mb-0">
        <li class="dropdown notification-list d-lg-none">
            <a class="nav-link dropdown-toggle arrow-none" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <i class="dripicons-search noti-icon"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-animated dropdown-lg p-0">
                <form class="p-3">
                    <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                </form>
            </div>
        </li>


        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle arrow-none" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <i class="dripicons-bell noti-icon"></i>
                <span class="noti-icon-badge"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated dropdown-lg">

                <!-- item-->
                <div class="dropdown-item noti-title">
                    <h5 class="m-0">
                        <span class="float-end">
                            <a href="javascript: void(0);" class="text-dark">
                                <small>Clear All</small>
                            </a>
                        </span>Notification
                    </h5>
                </div>

                <div style="max-height: 230px;" data-simplebar>
                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-primary">
                            <i class="mdi mdi-comment-account-outline"></i>
                        </div>
                        <p class="notify-details">
                            Caleb Flakelar commented on Admin
                            <small class="text-muted">1 min ago</small>
                        </p>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-info">
                            <i class="mdi mdi-account-plus"></i>
                        </div>
                        <p class="notify-details">
                            New user registered.
                            <small class="text-muted">5 hours ago</small>
                        </p>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon">
                            <img src="~/assets/images/users/avatar-2.jpg" class="img-fluid rounded-circle" alt="" />
                        </div>
                        <p class="notify-details">Cristina Pride</p>
                        <p class="text-muted mb-0 user-msg">
                            <small>Hi, How are you? What about our next meeting</small>
                        </p>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-primary">
                            <i class="mdi mdi-comment-account-outline"></i>
                        </div>
                        <p class="notify-details">
                            Caleb Flakelar commented on Admin
                            <small class="text-muted">4 days ago</small>
                        </p>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon">
                            <img src="~/assets/images/users/avatar-4.jpg" class="img-fluid rounded-circle" alt="" />
                        </div>
                        <p class="notify-details">Karen Robinson</p>
                        <p class="text-muted mb-0 user-msg">
                            <small>Wow ! this admin looks good and awesome design</small>
                        </p>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <div class="notify-icon bg-info">
                            <i class="mdi mdi-heart"></i>
                        </div>
                        <p class="notify-details">
                            Carlos Crouch liked
                            <b>Admin</b>
                            <small class="text-muted">13 days ago</small>
                        </p>
                    </a>
                </div>

                <!-- All-->
                <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
                    View All
                </a>

            </div>
        </li>

        <li class="dropdown notification-list d-none d-sm-inline-block">
            <a class="nav-link dropdown-toggle arrow-none" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <i class="dripicons-view-apps noti-icon"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated dropdown-lg p-0">

                <div class="p-2">
                    <div class="row g-0">
                        <div class="col">
                            <a class="dropdown-icon-item" href="#">
                                <img src="~/assets/images/brands/slack.png" alt="slack">
                                <span>Slack</span>
                            </a>
                        </div>
                        <div class="col">
                            <a class="dropdown-icon-item" href="#">
                                <img src="~/assets/images/brands/github.png" alt="Github">
                                <span>GitHub</span>
                            </a>
                        </div>
                        <div class="col">
                            <a class="dropdown-icon-item" href="#">
                                <img src="~/assets/images/brands/dribbble.png" alt="dribbble">
                                <span>Dribbble</span>
                            </a>
                        </div>
                    </div>

                    <div class="row g-0">
                        <div class="col">
                            <a class="dropdown-icon-item" href="#">
                                <img src="~/assets/images/brands/bitbucket.png" alt="bitbucket">
                                <span>Bitbucket</span>
                            </a>
                        </div>
                        <div class="col">
                            <a class="dropdown-icon-item" href="#">
                                <img src="~/assets/images/brands/dropbox.png" alt="dropbox">
                                <span>Dropbox</span>
                            </a>
                        </div>
                        <div class="col">
                            <a class="dropdown-icon-item" href="#">
                                <img src="~/assets/images/brands/g-suite.png" alt="G Suite">
                                <span>G Suite</span>
                            </a>
                        </div>
                    </div> <!-- end row-->
                </div>

            </div>
        </li>

        <li class="notification-list">
            <a class="nav-link end-bar-toggle" href="javascript: void(0);">
                <i class="dripicons-gear noti-icon"></i>
            </a>
        </li>

        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user arrow-none me-0" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false"
               aria-expanded="false">
                <span class="account-user-avatar">
                    <img src="~/assets/images/users/avatar-1.jpg" alt="user-image" class="rounded-circle">
                </span>
                <span>
                    <span class="account-user-name">Trần Văn Đức</span>
                    <span class="account-position">Quản trị viên</span>
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated topbar-dropdown-menu profile-dropdown">
                <!-- item-->
                <div class=" dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Xin chào !!!!</h6>
                </div>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="mdi mdi-account-circle me-1"></i>
                    <span>Tài khoản của tôi</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="mdi mdi-account-edit me-1"></i>
                    <span>Settings</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="mdi mdi-lifebuoy me-1"></i>
                    <span>Support</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="mdi mdi-lock-outline me-1"></i>
                    <span>Lock Screen</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="mdi mdi-logout me-1"></i>
                    <span>Đăng Xuất</span>
                </a>
            </div>
        </li>

    </ul>
    <button class="button-menu-mobile open-left">
        <i class="mdi mdi-menu"></i>
    </button>
    <div class="app-search dropdown d-none d-lg-block">
        <form>
            <div class="input-group">
                <input type="text" class="form-control dropdown-toggle" placeholder="Search..." id="top-search">
                <span class="mdi mdi-magnify search-icon"></span>
                <button class="input-group-text btn-primary" type="submit">Search</button>
            </div>
        </form>

        <div class="dropdown-menu dropdown-menu-animated dropdown-lg" id="search-dropdown">
            <!-- item-->
            <div class="dropdown-header noti-title">
                <h5 class="text-overflow mb-2">Found <span class="text-danger">17</span> results</h5>
            </div>

            <!-- item-->
            <a href="javascript:void(0);" class="dropdown-item notify-item">
                <i class="uil-notes font-16 me-1"></i>
                <span>Analytics Report</span>
            </a>

            <!-- item-->
            <a href="javascript:void(0);" class="dropdown-item notify-item">
                <i class="uil-life-ring font-16 me-1"></i>
                <span>How can I help you?</span>
            </a>

            <!-- item-->
            <a href="javascript:void(0);" class="dropdown-item notify-item">
                <i class="uil-cog font-16 me-1"></i>
                <span>User profile settings</span>
            </a>

            <!-- item-->
            <div class="dropdown-header noti-title">
                <h6 class="text-overflow mb-2 text-uppercase">Users</h6>
            </div>

            <div class="notification-list">
                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <div class="d-flex">
                        <img class="d-flex me-2 rounded-circle" src="~/assets/images/users/avatar-2.jpg" alt="Generic placeholder image" height="32">
                        <div class="w-100">
                            <h5 class="m-0 font-14">Erwin Brown</h5>
                            <span class="font-12 mb-0">UI Designer</span>
                        </div>
                    </div>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <div class="d-flex">
                        <img class="d-flex me-2 rounded-circle" src="~/assets/images/users/avatar-5.jpg" alt="Generic placeholder image" height="32">
                        <div class="w-100">
                            <h5 class="m-0 font-14">Jacob Deo</h5>
                            <span class="font-12 mb-0">Developer</span>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>